server:
  port: 8084
  servlet:
    context-path: /ui
    session:
      cookie:
        name: UISESSION



security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: ClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8081/auth/oauth/token
      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
#      scope: read
#      grant-type: authorization_code
      registered-redirect-uri: http://localhost:8084/ui/login
      pre-established-redirect-uri: http://localhost:8084/ui/login
#      authorities: CLIENT
      use-current-uri: false
    resource:
      userInfoUri: http://localhost:8081/auth/rest/hello/principal
#      prefer-token-info: false
      id: resource-server-rest-api


spring:
  thymeleaf:
    cache: false






